---
abstract: 'various utility functions'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Test::More: '0'
  Test::Warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
  strict: '0'
  warnings: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Munge
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '0'
  base: '0'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/mauke/Data-Munge.git
version: '0.08'
