---
abstract: 'various utility functions'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Munge
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 5.57
  Test::More: 0
version: 0.04
